version: "3.3"

services:
  app:
    build: 
      context: ./
      dockerfile: ./docker/app/Dockerfile   
    volumes:
      - ./src:/go/src/DXFimporter
      - ./resources:/resources
      - ./output:/output




  